#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

# Password
#PASS="ninth epidemic tamer scarring earache clamshell"

# Turn off firewall
sudo systemctl stop nftables

# pwd
# echo "Write up your solution below"
