#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

##################################################  VARS  ##################################################

netzh="aferrarini"
domain="$netzh.student.dtf.netsec.inf.ethz.ch"
acme_dir="https://acme.dtf.netsec.inf.ethz.ch/acme/default/directory"


################################################## TASK 1 ##################################################

# Remove line which blocks all traffic from conf file
sudo sed -i '/ct state established,related log prefix "DROPPING PACKET: " drop/d' /etc/nftables.conf

# Restart firewall
sudo systemctl restart nftables


################################################## TASK 2 ##################################################

# Load conf file to kernel and add new rule
sudo nft flush ruleset
sudo nft -f /etc/nftables.conf 
sudo nft add rule inet filter input ip saddr grader.dtf.netsec.inf.ethz.ch tcp dport {5432} accept
sudo nft add rule inet filter input tcp dport 5432 drop

# Dump conf file in kernel to conf file on disk
sudo chmod 777 /etc/nftables.conf
sudo nft list ruleset > /etc/nftables.conf
sudo chmod 755 /etc/nftables.conf

# Restart firewall
sudo systemctl restart nftables


################################################## TASK 3 ##################################################

# Change permissions on unencrypted passwords file
sudo chmod 600 /var/www/secret/passwords


################################################## TASK 4 ##################################################

# 0 - Download ACME client
rm -rf ../req_cert
mkdir ../req_cert
cd ../req_cert
git clone https://github.com/diafygi/acme-tiny.git

# 1 - Generate private key
sudo openssl genrsa 4096 > account.key

# 2 - Generate domain private key and CSR from the generated key
sudo openssl genrsa 4096 > domain.key
sudo openssl req -new -sha256 -key domain.key -subj "/CN=$domain" > domain.csr

# 3 - Serve challenge files
sudo mkdir -p /var/www/html/.well-known/acme-challenge

# 4 - Request certificate signing
sudo python3 ./acme-tiny/acme_tiny.py --account-key ./account.key\
	--csr ./domain.csr\
	--acme-dir /var/www/html/.well-known/acme-challenge\
	--directory-url $acme_dir\
	--disable-check	> ./signed_chain.crt

# 5 - Configuring certificate on NGINX
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.no_ssl
sudo chmod 777 /etc/nginx
sudo echo "
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    gzip on;

    server {
        listen 443;
        ssl on;
	server_name aferrarini.student.dtf.netsec.inf.ethz.ch;
	ssl_certificate $(pwd)/signed_chain.crt;
        ssl_certificate_key $(pwd)/domain.key;
    	
	location / {
        	root /var/www/html;
        	index index.html;
        }
    }
}
" > /etc/nginx/nginx.conf
sudo chmod 755 /etc/nginx

# 6 - Finally, restarting NGINX
sudo systemctl restart nginx


################################################## TASK 5 ##################################################
# --> Task 5 was already taken care of in task 4 during nginx.conf writing (TLS was made secure)
